spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: zxh000000
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: zxh000000

server:
  port: 9090

logging:
  level:
    root: WARN

mybatis:
  configuration:
    #开启mybatis驼峰式命名规则自动转换
    map-underscore-to-camel-case: true
